### ISSUE TITLE
Nombres en la Base de Datos ASAP!!!

### ISSUE THREAD

**Issue by DevHunvee3** [DevHunvee3/BD-Final#2]
Cambiar todos los nombres de absolutamente todo a minusculas.
La mayusculas causan problemas en los query siendo que si una tabla, ej: administradores, esta en minusculas, el query seria:
select * from administradores;

Mientras que si se llama Administradores, el query anterior no es valido y debera cambiar a:
select * from public."Administradores";

**Comment by Holdinait** [comment]
Forgot to close the issue, the last commit should have solved this
