### ISSUE TITLE
Nuevo usuario

### ISSUE THREAD

**Issue by DevHunvee3** [DevHunvee3/BD-Final#3]
Hable con pepe sobre como manejar el tema del logueo y me dijo que si bien el nunca lo hizo, lo correcto seria tener un tercer usuario con permisos de lectura solo en la tabla usuarios(comunes y administradores).
Lo importante seria ver como obtener de alguna forma de que table proviene, al hacer la busqueda, deberias buscar por administradores y por comunes, pero necesito que tmb el sp me diga si el usuario es administrador o no.
O de ultima que sean 2 sp, uno que busque en administradores y otro en usuarios. Y del lado de la aplicacion busco primero por administradores, si encuentra entonces termino ahi.
Si no encuentra entonces llamo al sp de comunes. Avisame si no entendes o si tenes otra idea.

**Comment by Holdinait** [comment]
El ultimo commit lo agrega, miralo por las dudas, los SPs los voy a anotar para hacerlos
